### ISSUE TITLE
Cannot use logical operators in consequent

### ISSUE THREAD

**Issue by stylianos-kampakis** [scikit-fuzzy/scikit-fuzzy#102]
Hi there,

In the documentation it is reported that it is possible to use negation in a consequent, but it seems that toolkit does not support it. It throws an assertion error.

**Comment by JDWarner** [comment]
Ping @jsexauer

**Comment by JDWarner** [comment]
@stylianos-kampakis I've been trying to reproduce this, and want to make sure we're seeing the same thing.

Could you provide a small example, so we know we're talking the same language?

**Comment by JDWarner** [comment]
Still having trouble reproducing this, or perhaps I'm just not going about it the same way.

As far as I can tell, the logical structure for combining Terms is agnostic to the fuzzy variable type. Can you post an example, @stylianos-kampakis? If it's still a problem despite recent fixes in #108, I'd like to get it fixed ASAP.

**Comment by wemily-amazon** [comment]
Hi, I think I ran into the same issue.

~~~~
$ curl https://raw.githubusercontent.com/scikit-fuzzy/scikit-fuzzy/0835dc0654bb146a90f0e7bf03558aca7888fe93/docs/examples/plot_tipping_problem_newapi.py > tipping.py

$ python tipping.py 
19.847607362

$ diff tipping.py tipping-operator.py 
110c110
< rule1 = ctrl.Rule(quality['poor'] | service['poor'], tip['low'])
---
> rule1 = ctrl.Rule(quality['poor'] | service['poor'], ~tip['low'])

$ python tipping-operator.py 
Traceback (most recent call last):
  File "tipping-operator.py", line 110, in <module>
    rule1 = ctrl.Rule(quality['poor'] | service['poor'], ~tip['low'])
  File "<...snip..>/skfuzzy/lib/python2.7/site-packages/skfuzzy/control/rule.py", line 69, in __init__
    self.consequent = consequent
  File "<...snip...>/skfuzzy/lib/python2.7/site-packages/skfuzzy/control/rule.py", line 156, in consequent
    raise ValueError("Unexpected consequent type")
ValueError: Unexpected consequent type
~~~~

**Comment by wemily-amazon** [comment]
Also, [the docs say](http://pythonhosted.org/scikit-fuzzy/api/skfuzzy.control.html#skfuzzy.control.Rule)

> Consequent terms serving as outputs from this rule. Multiple terms may be
> combined using operators | (OR), & (AND), ~ (NOT), and parentheticals to group
> terms.

Is that a copy-paste typo?  If not, what's the meaning of using OR or AND in a consequent?

**Comment by mcromptonjr** [comment]
Hi, I also have this issue.
The documentation does suggest that we should be able to use logical operators on consequents in rules, but this raised error seems to suggest otherwise.

Was there ever a resolution to this problem?

**Comment by mcromptonjr** [comment]
Looking through the code in [skfuzzy/control/rule.py](https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/control/rule.py), it seems that this just isn't a supported feature and the documentation incorrectly states that it is. The consequent validation code on lines 193-225 have no code allowing TermAggregates, nor are 'WeightedTermAggregates' even an implemented type to allow for such consequent types.

I would consider either marking this issue as a documentation issue or a feature request. I would prefer to mark it as a feature request as this would be a considerably powerful tool.

**Comment by bangen** [comment]
Hi,
I'm running into the same issue when trying to implement an 'is not' rule.  According to the documentation this should be possible by using '~', however I get the following error:

`rule4 = ctrl.Rule(ovc['rare'] & sp2['persists'] & splow['can'] ~ slope['cannot'], density['rare'])
                                                                   ^
SyntaxError: invalid syntax`

Just wondering if/when there will be a solution available.

Thanks!

**Comment by mcromptonjr** [comment]
Hey @bangen,
You seem to just have invalid syntax.
Your antecedent expression has a floating not between the splow['can'] and slope['cannot'] variables.
It should be `rule4 = ctrl.Rule(ovc['rare'] & sp2['persists'] & splow['can'] & ~slope['cannot'], density['rare'])`

**Comment by HendTayeb** [comment]
is there any other solution or method I can use multiple consequents with?

**Comment by AheeshGaur1** [comment]
Hi, I too have run across this issue. 

I want to create two consequent connected with a logical ( &) operator but despite the documentation saying it can be done, the kernel throws an error.  

rule7 = ctrl.Rule(antecedent = left_obstacle_us_sensor['far'] & front_obstacle_us_sensor['far'] & (right_obstacle_us_sensor['near'] or right_obstacle_tc_sensor['touch']) & target_angle['left'], consequent = (left_wheel_velocity['mid'] & right_wheel_velocity['slow']))

Can you please suggest a solution or a workaround?

Thanks

**Comment by enyucao** [comment]
Hi, 
Using "&" operator in consequent doesn't make sense. 
https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/control/rule.py#L65 The document might need to be updated.

Here is the correct way to use multiple consequents:  (output1['term1'], output2['term2'])
Check the code:
https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/control/rule.py#L210

**Comment by servetcoskun** [comment]
I don't think that is true @enyucao. If you were to call `control.Rule(antecedent1 & antecedent2, consequent1, consequent2)` the consequent2 argument would be the label and you might get a multiple same name labels error `ValueError: Input rule cannot have same label, 'solutionPhDown[OFF]', as any other rule.` I have tested this.

**Comment by NihalKarne** [comment]
@servetcoskun Can you post simple example. The above isnt working for me

**Comment by Rielbe** [comment]
@enyucao Thank you so much.

@servetcoskun Note that the consequents have to be put between additional parenthesis:
`control.Rule(antecedent1 & antecedent2, (output1['term1'], output2['term2']) )`
The solution given by @enyucao works.

**Comment by imars** [comment]
The manuals suggest that logical not (~) is possible in the antecedent as they are supposed to be but it always signals a syntax error for me. Does anyone have experience using something like antecedent1~antecedent2? I'm using version 0.3, the skfuzzy.control module, installed with conda.

**Comment by imars** [comment]
The manuals suggest that logical not (~) is possible in the antecedent as they are supposed to be but it always signals a syntax error for me. Does anyone have experience using something like antecedent1antecedent2? I'm using version 0.3, the skfuzzy.control module, installed with conda.

**Comment by imars** [comment]
The manuals suggest that logical not (~) is possible in the antecedent as they are supposed to be but it always signals a syntax error for me. Does anyone have experience using something like antecedent1~antecedent2? I'm using version 0.3, the skfuzzy.control module, installed with conda.

**Comment by imars** [comment]
The manuals suggest that logical not (~) is possible in the antecedent as they are supposed to be but it always signals a syntax error for me. Does anyone have experience using something like `antecedent1 ~ antecedent2`? I'm using version 0.3, the skfuzzy.control module, installed with conda.

**Comment by WysokiStudent** [comment]
Bump
Updating the online docs with the examples provided would be enough to close this issue.

Link to docs: https://pythonhosted.org/scikit-fuzzy/api/skfuzzy.control.html#skfuzzy.control.Rule

**Comment by egroj97** [comment]
Hi! Just wanted to comment that the documentation still states that we can have logical operators in the consequents. Which is not true.

**Comment by BrunoDucatiVazquez** [comment]
Hi can someone help me, I need that my consequent need to toggle between on or off depending on the conditions of inputs but I have no idea how to do it. Does someone knows how?

![asd](https://user-images.githubusercontent.com/86581876/161408328-b243c6ef-5b91-4ceb-9ee6-30de64cec80b.png)

this image above is an example of the output for consequent
