### ISSUE TITLE
Fuzzy Control Systems: The Tipping Problem

### ISSUE THREAD

**Issue by matejko94** [scikit-fuzzy/scikit-fuzzy#144]
I am running this example:
http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html

The problem line is:
    rule1.view()

I got error as following:

/usr/local/lib/python3.6/dist-packages/networkx/drawing/nx_pylab.py:126: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  b = plt.ishold()
/usr/local/lib/python3.6/dist-packages/networkx/drawing/nx_pylab.py:138: MatplotlibDeprecationWarning: pyplot.hold is deprecated.
    Future behavior will be consistent with the long-time default:
    plot commands add elements without first clearing the
    Axes and/or Figure.
  plt.hold(b)
/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py:917: UserWarning: axes.hold is deprecated. Please remove it from your matplotlibrc and/or style files.
  warnings.warn(self.msg_depr_set % key)
/usr/local/lib/python3.6/dist-packages/matplotlib/rcsetup.py:152: UserWarning: axes.hold is deprecated, will be removed in 3.0
  warnings.warn("axes.hold is deprecated, will be removed in 3.0")
Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/matej/Desktop/camps_analysis/code/nextPin/server/spd/scripts/osm_and_camps/ppp.py", line 34, in <module>
    rule1.view()
  File "/usr/local/lib/python3.6/dist-packages/skfuzzy/control/rule.py", line 247, in view
    ControlSystemVisualizer(self).view().show()
AttributeError: 'tuple' object has no attribute 'show'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/matej/Desktop/camps_analysis/code/nextPin/server/spd/scripts/osm_and_camps/ppp.py", line 34, in <module>
    rule1.view()
  File "/usr/local/lib/python3.6/dist-packages/skfuzzy/control/rule.py", line 247, in view
    ControlSystemVisualizer(self).view().show()
AttributeError: 'tuple' object has no attribute 'show'

**Comment by JDWarner** [comment]
All of the .view() methods now return both the matplotlib figure and the axis; previously it was only the figure object.  This allows further modification to the plot.

Looks like I missed updating the example.  For now, realize that .view() will return a tuple with two objects; set those to fig and ax, then use fig.show() to replicate the prior behavior.

The example will be updated shortly.

**Comment by matejko94** [comment]
Thank you very much, for quick response and help :)

**Comment by matejko94** [comment]
Ok sorry for next question, do you think print_state should work ? I use it like this:     print(tipping.print_state())

I get vierd error:
AttributeError: 'generator' object has no attribute 'next'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/matej/Desktop/camps_analysis/code/nextPin/server/spd/scripts/osm_and_camps/analyse_ml.py", line 74, in <module>
    a()
  File "/home/matej/Desktop/camps_analysis/code/nextPin/server/spd/scripts/osm_and_camps/analyse_ml.py", line 65, in a
    fuzzy_set()
  File "/home/matej/Desktop/camps_analysis/code/nextPin/server/spd/scripts/osm_and_camps/analyse_ml.py", line 49, in fuzzy_set
    print(tipping.print_state())
  File "/usr/local/lib/python3.6/dist-packages/skfuzzy/control/controlsystem.py", line 395, in print_state
    if self.ctrl.consequents.next().output[self] is None:
AttributeError: 'generator' object has no attribute 'next'

**Comment by scikit-fuzzy** [comment]
This is a separate issue, involving Python 2/3 compatibility.
Specifically, you must be using Python 3.x.

`print_state` is more or less a debug function for introspection and was
intended to be significantly overhauled; it works (in Python 2.x) but the
output and format has room for improvement.  If there are things anyone
would like to see from `print_state`, please speak up.

On Thu, Sep 14, 2017 at 10:16 AM, Matej Senožetnik <notifications@github.com

**Comment by matejko94** [comment]
I am using 3.6. I am interested to get output for all rules degree number.

**Comment by JDWarner** [comment]
This is now fixed in master, @matejko94 - Closed by #148 .
