### ISSUE TITLE
Control system creation

### ISSUE THREAD

**Issue by bbrighttaer** [scikit-fuzzy/scikit-fuzzy#182]
Hi, 
I am trying to work with about 240 rules (5 antecedents [3 terms each], 1 consequent) and it is taking close to 45 seconds for `ctrl.ControlSystem(rules)` to finish processing. However, for few rules, say 9, it takes about 0.0141 seconds for the same task. Is there any way to improve the control system creation speed?

**Comment by JDWarner** [comment]
@bbrighttaer Just seeing this after you closed it.  Did you resolve the problem on your own?  If so, if you don't mind sharing how/what you did it may be useful to others.

**Comment by bbrighttaer** [comment]
well, I realized there's a recursive call to ensure rules deconfliction...I guess... when creating a control system so I override that method to avoid that check since in my case there is no way such an event may happen. Since then, even for over 200 rules, it takes seconds to process it.

**Comment by JDWarner** [comment]
That sounds like a reasonable use case - you are certainly not the only one using a high number of rules.  

I don't think it would be the default behavior, but please feel free to contribute a patch with a keyword argument to disable the check in question!

**Comment by bbrighttaer** [comment]
okay, I'll work on that and issue a pull request when it is done.

**Comment by bbrighttaer** [comment]
Sorry, I have not been able to add it to the main project yet as I agreed to. However, it is a minor modification of the `addrule(self, rule)` method in controlsystem.py. I have created a gist on that to help fix your problem for now at [https://gist.github.com/bbrighttaer/48174624b7e70da1f6809159ca484e8d](url).
You can compare it with [https://github.com/scikit-fuzzy/scikit-fuzzy/blob/7b17f37a51abdcc3f17f5e8f7495b62e011aeace/skfuzzy/control/controlsystem.py#L91](url) to help clarify the modification and also ensure it fits your purpose.
The commented out the networkx part:
`self.graph = nx.compose(self.graph, rule.graph)
        try:
            self.add_rule_n(rule)
        except:
            pass`
Thanks.

**Comment by enyucao** [comment]
Hi @bbrighttaer , I just tried your solution, but got an error which didn't show up before commenting out the NX part.
```
Traceback (most recent call last):
  File "offline_safety_assessment.py", line 1022, in <module>
    risk_assessment_instance.input['type'] = 0
  File "/home/ecaoeny/debug_scikit_fuzzy/no_graph_checking/scikit-fuzzy-master/skfuzzy/control/controlsystem.py", line 169, in __setitem__
    raise ValueError("Unexpected input: " + key)
ValueError: Unexpected input: type
```
It seems because the `networkx` graph is not extended, so in [controlsystem.py Line165](https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/control/controlsystem.py#L165) `sim.ctrl.graph.nodes()` don't contain the nodes.

**Comment by enyucao** [comment]
Hi all,

An idea just came to my mind. If you are using a static control system, **saving the variant to the disk** is OK for me.

One can use **pickle** package or **cPickle** to do so.

This solution is not elegant but it can be a plan B if you are facing the same problem.

**Comment by rsavutiu** [comment]
I am facing the same issue now, with over 400 rules. Just to be sure, what you last suggest is to pickle the skfuzzy.control.ControlSystem instance?

**Comment by sunnychampthukral** [comment]
I am trying to work with about 2400 rules  and it is taking approximate 2 hours  for ctrl.ControlSystem(rules) to finish processing. Is there any way to improve the control system creation speed?

**Comment by sunnychampthukral** [comment]
> Sorry, I have not been able to add it to the main project yet as I agreed to. However, it is a minor modification of the addrule(self, rule) method in controlsystem.py. I have created a gist on that to help fix your problem for now at https://gist.github.com/bbrighttaer/48174624b7e70da1f6809159ca484e8d.
> You can compare it with https://github.com/scikit-fuzzy/scikit-fuzzy/blob/7b17f37a51abdcc3f17f5e8f7495b62e011aeace/skfuzzy/control/controlsystem.py#L91 to help clarify the modification and also ensure it fits your purpose.
> The commented out the networkx part:
> self.graph = nx.compose(self.graph, rule.graph) try: self.add_rule_n(rule) except: pass
> Thanks.
I AM NOT GEETING THE SOLUTION WITH THIS CODE

**Comment by bbrighttaer** [comment]
Hello everyone,
Sorry for the delay and initial post.

I have updated the gist to contain the right modification I made:
https://gist.github.com/bbrighttaer/48174624b7e70da1f6809159ca484e8d
The slight modification is commenting out 
```python
self._cache = list(self._process_rules(self.all_rules[:]))
```
and adding 

```python
self._cache = list(self.all_rules[:])
self._cached_graph = self.control_system.graph
```
This can be seen beginning from line 41 of the gist.

My review of the original method [`_process_rules()`](https://github.com/scikit-fuzzy/scikit-fuzzy/blob/7b17f37a51abdcc3f17f5e8f7495b62e011aeace/skfuzzy/control/controlsystem.py#L758) showed that it performs recursive calls to process and validate the rules of the control system. Hence, having a large rule set leads to longer processing times. In my opinion, the benefit you get from the function in question is ensuring all rules are not in conflict and are also executed in the correct order. Since my work did not have to worry about that, I found it unnecessary.

Below is an example usage:
```python
import skfuzzy.control as ctrl
# I store all modified/customized skfuzzy files in a local package named skfuzzext.
from .skfuzzext import RuleGenerator

# create a control system
ctrlsys = ctrl.ControlSystem()

# set a custom rule generator
ctrlsys._rule_generator = RuleGenerator(ctrlsys)

# Rules could then be added. Assuming I have a list of rules:
for rule in rules:
    ctrlsys.addrule(rule)

# create a control system simulation
ctrlsim = ctrl.ControlSystemSimulation(control_system=ctrlsys)

# application specific codes could then follow
```
I think I would be able to give quicker responses at the moment so in case of any bug, pertaining to this issue, please post it here and I would be glad to help resolve it.
Thanks.

**Comment by sunnychampthukral** [comment]
Myself Sunny Thukral, assistant professor in department of computer science from last 10 years. I am working on a system that having 15,000 fuzzy
rules with 6 variables. I want to get the information regaining the speed of the system. If I run only 540 rules in Python as , it takes 40 minutes to reply the de fuzzification value. Is there any othet procedure to compute only fuzzy matched rules.
Waiting for the positive reply.
from line 41 of the gist.

My review of the original method _process_rules() showed that it performs recursive calls to process and validate the rules of the control system. Hence, having a large rule set leads to longer processing times. In my opinion, the benefit you get from the function in question is ensuring all rules are not in conflict and are also executed in the correct order. Since my work did not have to worry about that, I found it unnecessary.

Below is an example usage:
import skfuzzy.control as ctrl
# I store all modified/customized skfuzzy files in a local package named skfuzzext.
from .skfuzzext import RuleGenerator

# create a control system
ctrlsys = ctrl.ControlSystem()

# set a custom rule generator
ctrlsys._rule_generator = RuleGenerator(ctrlsys)

# Rules could then be added. Assuming I have a list of rules:
for rule in rules:
    ctrlsys.addrule(rule)

# create a control system simulation
ctrlsim = ctrl.ControlSystemSimulation(control_system=ctrlsys)

# application specific codes could then follow
I think I would be able to give quicker responses at the moment so in case of any bug, pertaining to this issue, please post it here and I would be glad to help resolve it.
Thanks.

**Comment by sunnychampthukral** [comment]
Your technique works exactly to reduce the tym. Hats off to u. But for 1000 rules taking 1 minute and for 2500 rules still taking 6 minutes. Still it is possible to reduce the computation time?

**Comment by sunnychampthukral** [comment]
@bbrighttaer, thanks once again, if feasible resolve 6 min to les so that further accessing can be improved

**Comment by bbrighttaer** [comment]
I'm glad to know it helped. About your question, I will set up a use case of that nature and investigate it further if any other aspect could be improved.
All the best!

**Comment by JDWarner** [comment]
I'd be perfectly happy to merge a patch which exposed this alternative (basically "safety off") as the non-default option for these types of cases.

**Comment by sunnychampthukral** [comment]
@JDWarner, y u reffered as safety off, I am getting same output, but for 5000 rules still getting 15 min approx, Still I am working to reduce or merging the rules.

**Comment by JDWarner** [comment]
The underlying rule execution system is a directed graph.  It will break - badly - if you craft specific Rule combinations which depend on each other or result in loops in the graph.  The recursive call this patch avoids exists because some users might naively create such combinations, which result in either infinite computation loops or crashes.

If you create proper Rules and systems, this isn't a problem and it has trouble scaling.  So I'm all right having the ability to disable it, but not as the default case.  It's worth noting this is only in the system creation, not in its execution, so for a given system you pay the price only once.
