### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by aiwarrior-23** [scikit-fuzzy/scikit-fuzzy#202]
I am getting the following error when I am trying to add the rules in control system:

Traceback (most recent call last):
  File "example.py", line 35, in <module>
    tipping_ctrl = control.ControlSystem([rule1, rule2, rule3])
  File "D:\Anaconda_Notebooks\scikit-fuzzy\skfuzzy\control\controlsystem.py", line 47, in __init__
    self.addrule(rule)
  File "D:\Anaconda_Notebooks\scikit-fuzzy\skfuzzy\control\controlsystem.py", line 100, in addrule
    for r in self.rules:
  File "D:\Anaconda_Notebooks\scikit-fuzzy\skfuzzy\control\controlsystem.py", line 730, in __iter__
    self._cache = list(self._process_rules(self.all_rules[:]))
**RuntimeError: generator raised StopIteration**

**Comment by kochab** [comment]
This happens on Python 3.7 and is a consequence of [PEP 479](https://www.python.org/dev/peps/pep-0479/)

**Comment by JDWarner** [comment]
This is a really irritating PEP.  We are in fact an edge case where we wanted this behavior.  

Now working on a patch for this, can reproduce in Anaconda 3.7.1.
