### ISSUE TITLE
Use enum or constants for partial_dmf membership function parameter values

### ISSUE THREAD

**Issue by kinow** [scikit-fuzzy/scikit-fuzzy#239]
At the moment skfuzzy.fuzzymath.fuzzy_ops.partial_dmf takes a string as parameter. It then does an `if/elif` chain of statements to choose the membership function according to the argument given.

However, if the user provides an invalid value, it will raise an `UnboundLocalError`. e.g.

```py
>>> from skfuzzy.fuzzymath.fuzzy_ops import partial_dmf
>>> partial_dmf(x=0.5, mf_name='applied_1', mf_parameter_dict={}, partial_parameter='temp1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kinow/Development/python/workspace/scikit-fuzzy/skfuzzy/fuzzymath/fuzzy_ops.py", line 864, in partial_dmf
    return result
UnboundLocalError: local variable 'result' referenced before assignment
>>> 
```

We could also add an 

```py
    else:
        raise ValueError("Invalid membership function...")
```

But an enum or constant could be used instead, to provide a list of valid values to be chosen by users, removing the possibility of a `ValueError` - or `UnboundLocalError`.

**Comment by kinow** [comment]
(There are probably other methods in a similar fashion that could use the same approach.)

**Comment by JDWarner** [comment]
I approve, and would welcome a PR to this effect.

**Comment by kinow** [comment]
Note: to self or to other contributor that decide to help with this, probably a good idea to check Py2 compatibility. Off the top of my head, enums were added in Py3. For py2 one would have to install an extra `enum` module. So perhaps the class constants would be easier.
