### ISSUE TITLE
print_state() is not working in skfuzzy.control.ControlSystemSimulation(...)

### ISSUE THREAD

**Issue by Dhyeythumar** [scikit-fuzzy/scikit-fuzzy#272]
- OS Platform and Distribution: Windows 10 20H2
- Python version: 3.8.3

I am working with skfuzzy.control.ControlSystemSimulation() and found this error:

**Standalone code to reproduce the issue:**
https://colab.research.google.com/drive/1bio1aSZw31YddqQWVRWH1Gwx-4ObDW6W

**Error:**
```bash
=============
 Antecedents 
=============
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-5adb642f1f83> in <module>()
     57 
     58     washing_machine.compute()
---> 59     washing_machine.print_state()
     60     print(
     61         "\n\tWash-time for {} % Dirt & {} % Grease: {}".format(

/usr/local/lib/python3.6/dist-packages/skfuzzy/control/controlsystem.py in print_state(self)
    502         print("=============")
    503         for v in self.ctrl.antecedents:
--> 504             print("{0:<35} = {1}".format(v, v.input[self]))
    505             for term in v.terms.values():
    506                 print("  - {0:<32}: {1}".format(term.label,

TypeError: unsupported format string passed to Antecedent.__format__
```

And there are multiple such error so I modified the source code of print_state() function in controlsystem.py file.

But after making changes I got following error:
```bash
==============================
 Intermediaries and Conquests
==============================
Consequent: wash_time                = 55.5
  VS:
Traceback (most recent call last):
  File "FLC.py", line 65, in <module>
    washing_machine.print_state()
  File "C:\Users\dhyey\AppData\Local\Programs\Python\Python38\lib\site-packages\skfuzzy\control\controlsystem.py", line 543, in print_state
    accu = "Accumulate using %s" % c.accumulation_method.func_name
AttributeError: 'function' object has no attribute 'func_name'
```

So I modified `c.accumulation_method.func_name` to `c.accumulation_method.__name__`

**Comment by Dhyeythumar** [comment]
I checked the code on this repo and its working, so I think code in package is not update.

- Package version:  0.4.2

**Comment by Dhyeythumar** [comment]
I checked the code on this repo and it is working, so I think the python package is not up to date.

**Comment by JDWarner** [comment]
Yes, we need to push a new version to PyPi and Conda.  I'm hoping to have the documentation improvements from #260 in before that release.  Until then I will leave this open.

**Comment by cora2406** [comment]
There is still no new version in PyPi/Conda with this fix. I use this package in class and using pip ou conda would make my students' life much easier. Is there a planned release soon?
