### ISSUE TITLE
Unable to install scikit-fuzzy

### ISSUE THREAD

**Issue by xnicolegracex** [scikit-fuzzy/scikit-fuzzy#297]
Collecting scikit-fuzzy
  Using cached scikit-fuzzy-0.4.2.tar.gz (993 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-fuzzy) (1.24.1)
Collecting scipy>=0.9.0
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165
      Build dir: /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-yyg70xxs/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
      C linker for the host machine: cc ld64 609.8
      C++ compiler for the host machine: c++ (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
      C++ linker for the host machine: c++ ld64 609.8
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-yyg70xxs/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Library/Frameworks/Python.framework/Versions/3.9 /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165 /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-yyg70xxs/build --native-file=/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-hmdjofxk/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/Library/Frameworks/Python.framework/Versions/3.9', '/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165', '/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-yyg70xxs/build', '--native-file=/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-n6xaw5b1/scipy_3fadd91d88024d09a38cb5a4ebda3165/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 

I keep getting this error when I'm trying to install it on my visual studio code. How can I fix this?

**Comment by eli-schwartz** [comment]
The build log reports that SciPy, one of the dependencies, failed to build.

(Specifically, the error states that you do not have a Fortran compiler installed, and SciPy requires one to build from source.)

https://pypi.org/project/scipy/#files

SciPy has published wheels for arm64 macOS 12.0, and for x86_64 macOS 10.15, which does not cover your use case :( this is why pip attempted to build it from source instead.

**Comment by xnicolegracex** [comment]
I see, so since it does not cover my use case. How can I solve this issue? I really need to install skfuzzy for my project

**Comment by eli-schwartz** [comment]
You could try to install a Fortran compiler as the error message suggested. :)

Alternatively you could upgrade to macOS 12.0 or higher...

**Comment by xnicolegracex** [comment]
Collecting scikit-fuzzy
  Using cached scikit-fuzzy-0.4.2.tar.gz (993 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-fuzzy) (1.24.1)
Collecting scipy>=0.9.0
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a
      Build dir: /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-syit08yp/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
      C linker for the host machine: cc ld64 609.8
      C++ compiler for the host machine: c++ (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.29)")
      C++ linker for the host machine: c++ ld64 609.8
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:63:0: ERROR: Compiler gfortran can not compile programs.
      
      A full log can be found at /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-syit08yp/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Library/Frameworks/Python.framework/Versions/3.9 /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-syit08yp/build --native-file=/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
          return next(self.gen)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-build-env-jii2c0iv/overlay/lib/python3.9/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/Library/Frameworks/Python.framework/Versions/3.9', '/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a', '/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-syit08yp/build', '--native-file=/private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output] 

hey I've install a Fortran compiler but it still is giving me an error. Is there any way? I've asked help from others but no one could figure it out

**Comment by eli-schwartz** [comment]
```
../../meson.build:63:0: ERROR: Compiler gfortran can not compile programs.
  
  A full log can be found at /private/var/folders/n_/2tsm1fcx28q1cfkmx5yzfvx00000gn/T/pip-install-ue6kffui/scipy_4000f28c8ffa4cd2aa13c3e38dfc374a/.mesonpy-syit08yp/build/meson-logs/meson-log.txt
```

It's saying that the compiler you installed does not work. :/

There's a log file with more details, but pip has a habit of deleting failed builds. You can try to build SciPy manually and see if it works:
- from https://pypi.org/project/scipy/#files download the "Source Distribution" file
- extract it
- run `python -m pip install build`
- inside the SciPy directory, run `python -m build --wheel -Cbuilddir=builddir
