### ISSUE TITLE
Documentation build issues

### ISSUE THREAD

**Issue by erasche** [scikit-fuzzy/scikit-fuzzy#62]
Howdy devs, Would it be possible to:

- [ ] turn on readthedocs for sk-fuzzy? 
- [ ] provide a full requirements.txt (numpy, scipy, scikit-image, matplotlib)

I've not actually been able to build the docs myself yet, and would really like to read them in HTML since it looks like really well written documentation

```
(env)hxr@leda:~/work/scikit-fuzzy/docs$ make html
python tools/build_modref_templates.py
('outdir: ', '')
8 files written
Build API docs...done.
python tools/gitwash/gitwash_dumper.py source scikit-fuzzy \
--project-url=http://scikit-fuzzy.org \
--project-ml-url=http://groups.google.com/group/scikit-fuzzy \
--repo-name=scikit-fuzzy \
--github-user=scikit-fuzzy \
--source-suffix=.txt
Cloning into '/tmp/tmpTTq5J1'...
remote: Counting objects: 649, done.
remote: Total 649 (delta 0), reused 0 (delta 0), pack-reused 649
Receiving objects: 100% (649/649), 216.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (387/387), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
python /home/hxr/work/scikit-fuzzy/env/bin/sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created

Exception occurred:
  File "/home/hxr/work/scikit-fuzzy/docs/ext/plot2rst.py", line 195, in generate_examples_and_gallery
    gallery_index = file(rst_dir.pjoin('index'+cfg.source_suffix), 'w')
TypeError: cannot concatenate 'str' and 'list' objects
The full traceback has been saved in /tmp/sphinx-err-KKSRL0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:49: recipe for target 'html' failed
make: *** [html] Error 1
```

The traceback

```
# Sphinx version: 1.3.1
# Python version: 2.7.9 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/hxr/work/scikit-fuzzy/env/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/hxr/work/scikit-fuzzy/env/local/lib/python2.7/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/home/hxr/work/scikit-fuzzy/env/local/lib/python2.7/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/home/hxr/work/scikit-fuzzy/env/local/lib/python2.7/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/home/hxr/work/scikit-fuzzy/docs/ext/plot2rst.py", line 184, in generate_example_galleries
    generate_examples_and_gallery(example_dir, rst_dir, cfg)
  File "/home/hxr/work/scikit-fuzzy/docs/ext/plot2rst.py", line 195, in generate_examples_and_gallery
    gallery_index = file(rst_dir.pjoin('index'+cfg.source_suffix), 'w')
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by JDWarner** [comment]
Thanks for the report, @erasche! Looks like I need to update my Sphinx - the compilation issue you're seeing is a bug due to a change in Sphinx 1.3. I've identified a couple other minor issues with the doc build which will be fixed shortly, such as automated trigger of the logo build.

I think `scikit-image` is only required to build the package logo, so I'm reluctant to introduce a fairly large dependency which isn't necessary to run/use the package. Similarly, I think `matplotlib` is only used in the gallery. I'd be open to thoughts regarding how best to handle this.

**Comment by erasche** [comment]
Thanks @JDWarner for the quick reply! Agreed, those are heavy weight dependencies for building logos/images (but a really amusing/great use of them.) 

I'm not sure I have great suggestions on dependencies only required for building docs, I imagine a `requirements-dev.txt` or similar is probably your best bet, you could write one like the following (I'm ~80% sure that's this is the appropriate syntax)

```
-r requirements.txt
scikit-image
matplotlib
```

which would extend anything in requirements.txt and install all of it for us pip users. I'm not sure how that's handled on the RTD side (or whatever other doc build service you might use).

**Comment by JDWarner** [comment]
How do you feel about `requirements-docs.txt` as it's perfectly possible to develop `scikit-fuzzy` without these packages?

**Comment by erasche** [comment]
Sure, that would be great!
